# Generated by Django 5.1.2 on 2024-10-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cor_principal', models.CharField(max_length=1000)),
                ('cor_detalhes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='images/estacoes/<django.db.models.fields.CharField>/logo')),
                ('descricao_estacao', models.TextField(max_length=2000)),
                ('texto_funcionamento', models.TextField(max_length=1000)),
                ('servico1', models.TextField(max_length=100)),
                ('servico2', models.TextField(max_length=100)),
                ('servico3', models.TextField(max_length=100)),
                ('responsabilidade', models.CharField(max_length=1000)),
                ('beneficio1', models.TextField(max_length=1000)),
                ('beneficio2', models.TextField(max_length=1000)),
                ('beneficio3', models.TextField(max_length=1000)),
                ('ideal_para1', models.TextField(max_length=1000)),
                ('ideal_para2', models.TextField(max_length=1000)),
                ('ideal_para3', models.TextField(max_length=1000)),
                ('competencia', models.TextField(max_length=1000)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cores')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/estacoes/None/beneficios')),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estacao')),
            ],
        ),
        migrations.CreateModel(
            name='Ideal_para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/global/cores/<django.db.models.fields.related.ForeignKey>/ideal_para')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cores')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens_beneficios_cores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/global/cores/<django.db.models.fields.related.ForeignKey>/beneficios')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cores')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens_equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/estacoes/None/equipe')),
                ('alt', models.CharField(max_length=100)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.estacao')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/global/cores/<django.db.models.fields.related.ForeignKey>/servicos')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cores')),
            ],
        ),
    ]
