# Generated by Django 5.1.2 on 2024-10-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacao',
            old_name='competencia',
            new_name='competencia1',
        ),
        migrations.AddField(
            model_name='estacao',
            name='competencia2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacao',
            name='competencia3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
