# Generated by Django 5.1.2 on 2024-10-23 17:46

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='imagem',
            field=models.ImageField(upload_to=Core.models.Servicos.gerar_rota),
        ),
    ]
