# Generated by Django 5.1.2 on 2024-10-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_competencia_estacao_competencia1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='alt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideal_para',
            name='alt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
