# Generated by Django 5.1.2 on 2024-10-23 18:03

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_servicos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficios',
            name='imagem',
            field=models.ImageField(upload_to=Core.models.Beneficios.gerar_rota),
        ),
        migrations.AlterField(
            model_name='cores',
            name='cor_detalhes',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='cores',
            name='cor_principal',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='logo',
            field=models.ImageField(upload_to=Core.models.Estacao.gerar_rota),
        ),
        migrations.AlterField(
            model_name='ideal_para',
            name='imagem',
            field=models.ImageField(upload_to=Core.models.Ideal_para.gerar_rota),
        ),
        migrations.AlterField(
            model_name='imagens_beneficios_cores',
            name='imagem',
            field=models.ImageField(upload_to=Core.models.Imagens_beneficios_cores.gerar_rota),
        ),
        migrations.AlterField(
            model_name='imagens_equipe',
            name='imagem',
            field=models.ImageField(upload_to=Core.models.Imagens_equipe.gerar_rota),
        ),
    ]
