# Generated by Django 5.1.2 on 2024-10-23 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_beneficios_imagem_alter_cores_cor_detalhes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficios',
            name='estacao',
        ),
        migrations.AddField(
            model_name='beneficios',
            name='cor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.cores'),
            preserve_default=False,
        ),
    ]
